version: '3.3'

services:
  outboxtable-job:
    container_name: outboxtable-job
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8082:8080
    environment:
      - AWS_REGION=${region}
      - AWS_ACCESS_KEY=${access_key}
      - AWS_SECRET_ACCESS_KEY=${secret_access_key}
    networks: 
      - base_default
      
networks: 
  base_default:
    external: true      
