CREATE DATABASE outboxtable_db;

USE outboxtable_db;

CREATE TABLE obt_spending (

 ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 IDENTITY VARCHAR(10) NOT NULL,
 NAME VARCHAR(100) NOT NULL,
 SURNAME VARCHAR(100) NOT NULL,
 AMOUNT DECIMAL(20,2) UNSIGNED NOT NULL,
 PRIMARY KEY (ID),
 UNIQUE INDEX (IDENTITY)

);

CREATE TABLE obt (

 ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 IDENTITY VARCHAR(10) NOT NULL,
 MESSAGE VARCHAR(1000) NOT NULL,
 INTEGRATED TINYINT(1) NOT NULL,
 PRIMARY KEY (ID),
 UNIQUE INDEX (IDENTITY)

);

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'mdymen_pass';
